### ISSUE TITLE
Crashing on application start

### ISSUE THREAD

**Issue by ComeSeeMePlay** [feelfar/varManager#18]
Very often when starting varManager v1.0.4.2 the application crashes and after repeated tries it opens.

`Faulting application name: varManager.exe, version: 1.0.4.2, time stamp: 0x922a27a6
Faulting module name: mso.dll_unloaded, version: 16.0.15726.20096, time stamp: 0x6342939d
Exception code: 0xc0000005
Fault offset: 0x0000000000172700
Faulting process id: 0x0x3D84
Faulting application start time: 0x0x1D8E00B831E69F5
Faulting module path: mso.dll
Report Id: ecf7c375-06ff-4a41-8bf9-8d56c94c64c5
Faulting package full name: 
Faulting package-relative application ID: `

`
Application: varManager.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(System.Data.OleDb.OleDbConnectionString, System.Data.OleDb.DataSourceWrapper ByRef)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(System.Data.OleDb.OleDbConnectionString, System.Data.OleDb.OleDbConnection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions, System.Data.Common.DbConnectionPoolKey, System.Object, System.Data.ProviderBase.DbConnectionPool, System.Data.Common.DbConnection)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionPoolGroup, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions, System.Data.ProviderBase.DbConnectionInternal, System.Data.ProviderBase.DbConnectionInternal ByRef)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory, System.Threading.Tasks.TaskCompletionSource`1<System.Data.ProviderBase.DbConnectionInternal>, System.Data.Common.DbConnectionOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(System.Data.Common.DbConnection, System.Data.ProviderBase.DbConnectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at varManager.varManagerDataSetTableAdapters.installStatusTableAdapter.DeleteAll()
   at varManager.Form1.UpdateVarsInstalled()
   at varManager.Form1.Form1_Load(System.Object, System.EventArgs)
   at System.Windows.Forms.Form.OnLoad(System.EventArgs)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

`

**Comment by feelfar** [comment]
Sorry for the trouble, this may be caused by the var file decompression analysis error. Please upgrade to v1046 version first, open the varmanager.mdb file with access, check the vars table, see whether the version,metadate,vardate fields have empty values, if so, please delete these records, and then run the tool to see if it is normal, and then updDB to see if there is a prompt error.

**Comment by ComeSeeMePlay** [comment]
Still crashes with v1046, but after 5-10 tries it works.
At the same time it seems like the mdb file is unreadable and i think that is why.

Does the mdb file get locked somehow?

**Comment by feelfar** [comment]
try compact and repair by access

**Comment by VAM-Kitten** [comment]
I've been getting this error since I think 1.0.3.1. What is weird, I get it only on one PC. On the second one, also Windows 10, I don't get it at all, not even once. The second PC's system is much cleaner though, not many applications installed there.
