### ISSUE TITLE
Exception due to typo in 'missing var' module

### ISSUE THREAD

**Issue by ghost** [feelfar/varManager#34]
This has been bugging me for ages: 

Everytime I search for missing vars (Installed packages, All Packages etc), an exception is thrown, and the Exception handler complains it can't find part of the path '[Vam_Root]\AddonPackages\___MissingVarLink___\ plugin)' ...

Well, course it can't find that file, bcs " plugin)" doesn't exist (and there's no reason for a file with that name to exist)

This looks like a typo in the sourcecode - COULD YOU PLEASE FIX THIS?

--------------------------- Exception Text ------------------------
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\3x_Games_C\VaM\Virt-A-Mate Big\AddonPackages\___MissingVarLink___\ plugin)'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at varManager.FormMissingVars.FillMissVarGridView() in D:\a\varManager\varManager\varManager\FormMissingVars.cs:line 145
   at varManager.FormMissingVars.toolStripComboBoxIgnoreVersion_SelectedIndexChanged(Object sender, EventArgs e) in D:\a\varManager\varManager\varManager\FormMissingVars.cs:line 506
   at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by CaseEP** [comment]
Found the source of the exception: A meta.json file with huge blocks of texts in the "Instructions" and "Credits" fields, formatted with CR and linefeed characters (like eg \n etc). 

It would probably be nice if varmanager's JSON parser could be taught to ignore stuff like that, but I don't know if that's possible or feasible.

So I'm closing this issue.

**Comment by ghost** [comment]
Found the source of the exception: A meta.json file with huge blocks of texts in the "Instructions" and "Credits" fields, formatted with CR and linefeed characters (like eg \n etc). 

The "\ plugin)" string was part of that block of text-

It would probably be nice if varmanager's JSON parser could be taught to ignore stuff like that, but I don't know if that's possible or feasible.

So I'm closing this issue.
